# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
pre_build:
  - apt-get update && apt-get install -y r-base  # 安装 R
  - export R_HOME=/usr/lib/R                     # 设置 R_HOME
  - export PATH=$PATH:/usr/lib/R/bin  
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
sphinx:
  configuration: docs/source/conf.py
  # disable this for more lenient docs builds
  fail_on_warning: false
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docsbuild
submodules:
    include: [docs/source/Tutorials]
    recursive: true
