# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  apt_packages:
    - r-base         # 安装 R 语言环境
    - r-base-dev 
 # environment:
 #  RPY2_CFFI_MODE: "ABI"
  commands:
    - export R_HOME=$(R RHOME)
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html
sphinx:
  configuration: docs/source/conf.py
  # disable this for more lenient docs builds
  fail_on_warning: false
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docsbuild
submodules:
    include: [docs/source/Tutorials]
    recursive: true
