# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
 jobs:
  pre_install:
    - sudo apt-get update
    - sudo apt-get install -y r-base r-base-dev
    - export R_HOME="/usr/lib/R"
    - export RPY2_CFFI_MODE="ABI"
sphinx:
  configuration: docs/source/conf.py
  # disable this for more lenient docs builds
  fail_on_warning: false
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docsbuild
submodules:
    include: [docs/source/Tutorials]
    recursive: true
